[package]
name = "pngme"
version = "1.0.0"
authors = ["Steven Waldron <steven.waldron@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
crc = "1"
structopt = "0.3"
